### ISSUE TITLE
Sharing iP code quality feedback [for @guowei42]

### ISSUE THREAD

**Issue by nus-se-script** [guowei42/ip#5]
@guowei42 We did an automated analysis of your code to detect potential areas to improve the code quality. We are sharing the results below, to help you improve the iP code further.

IMPORTANT: Note that the script looked for **just a few easy-to-detect problems only**, and **at-most three example are given** i.e., there can be other areas/places to improve.

### Aspect: Tab Usage

No easy-to-detect issues :+1: 

### Aspect: Naming boolean variables/methods

Example from [`src/main/java/deku/task/Task.java` lines `19-19`](https://github.com/guowei42/ip/blob/e15a21b42e3d2c1eaaab397f42594e05d9a107f8/src/main/java/deku/task/Task.java#L19..L19):

```java

    private Boolean completionStatus;

``` 

**Suggestion:** Follow the given naming convention for boolean variables/methods (e.g., use a boolean-sounding prefix).You may ignore the above if you think the name already follows the convention (the script can report false positives in some cases)

### Aspect: Brace Style

No easy-to-detect issues :+1: 

### Aspect: Package Name Style

No easy-to-detect issues :+1: 

### Aspect: Class Name Style

No easy-to-detect issues :+1: 

### Aspect: Dead Code

No easy-to-detect issues :+1: 

### Aspect: Method Length

No easy-to-detect issues :+1: 

### Aspect: Class size

No easy-to-detect issues :+1: 

### Aspect: Header Comments

Example from [`src/main/java/deku/Deku.java` lines `24-29`](https://github.com/guowei42/ip/blob/e15a21b42e3d2c1eaaab397f42594e05d9a107f8/src/main/java/deku/Deku.java#L24..L29):

```java

    /**
     * Output message by deku
     *
     * @param input content Deku will say
     * @return Full string of the reply by Deku
     */

```

Example from [`src/main/java/deku/task/Task.java` lines `106-110`](https://github.com/guowei42/ip/blob/e15a21b42e3d2c1eaaab397f42594e05d9a107f8/src/main/java/deku/task/Task.java#L106..L110):

```java

    /**
     * Parse the current task to custom data structure to write to file for storage
     *
     * @return custom data structure for file
     */

```

Example from [`src/main/java/deku/ui/MainWindow.java` lines `50-54`](https://github.com/guowei42/ip/blob/e15a21b42e3d2c1eaaab397f42594e05d9a107f8/src/main/java/deku/ui/MainWindow.java#L50..L54):

```java

    /**
     * Set the logic for the input Deku class.
     *
     * @param d A new instance for Deku bot class
     */

``` 

**Suggestion:** Ensure method/class header comments follow the format specified in the coding standard, in particular, the phrasing of the overview statement.

### Aspect: Recent Git Commit Message (Subject Only)

No easy-to-detect issues :+1: 

### Aspect: Binary files in repo

No easy-to-detect issues :+1: 

:information_source: The bot account used to post this issue is un-manned. **Do not reply to this post** (as those replies will not be read). Instead, contact `cs2103@comp.nus.edu.sg` if you want to follow up on this post.

**Comment by guowei42** [comment]
[fixed](https://github.com/guowei42/ip/commit/a363711150ee7ba167246c0ff019a09fa7b04d50)
